# Generated by Django 3.0.7 on 2020-11-21 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=123, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=123, null=True)),
                ('age', models.PositiveIntegerField()),
                ('text_field', models.TextField()),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basic_app.Name')),
            ],
        ),
    ]
