# Generated by Django 3.0.7 on 2020-11-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=123, null=True),
        ),
        migrations.DeleteModel(
            name='Name',
        ),
    ]
